"""
SQLAlchemy Content Model
Defines the Content table schema for SQLite database
"""

from sqlalchemy import Column, Integer, String, Text, DateTime
from sqlalchemy.ext.declarative import declarative_base
from datetime import datetime

Base = declarative_base()


class Content(Base):
    """Content model for storing SEO content generated by AI"""
    
    __tablename__ = "content"
    
    id = Column(Integer, primary_key=True, index=True)
    topic = Column(String(255), nullable=False, index=True)
    title = Column(String(255), nullable=False)
    content = Column(Text, nullable=False)
    meta_title = Column(String(255), nullable=False)
    meta_description = Column(String(160), nullable=False)
    seo_score = Column(Integer, default=0)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    def __repr__(self):
        return f"<Content(id={self.id}, topic={self.topic}, seo_score={self.seo_score})>"
